platform :ios, '13.0'

target 'Gitwise' do

   pod 'XCoordinator', '~> 2.0'

   pod 'RxSwift', '6.2.0'
   pod 'RxDataSources', '~> 5.0'
   pod 'RxCocoa', '6.2.0'

   pod 'SkeletonView'
   
   pod 'RealmSwift', '=10.7', :modular_headers => true
   pod 'Realm', '=10.7', :modular_headers => true

   pod 'SnapKit', '~> 5.0.0'

   pod 'Moya', '~> 14.0'

end
